### ISSUE TITLE
Expert Effects regaining timing

### ISSUE THREAD

**Issue by Dima793** [Heegu-sama/Homm3BG#675]
In the current version it's said that Expert Effect uses are regained at the start of each round (page 11, left column, second paragraph)
![Screenshot_20240831-152615_Firefox_Beta](https://github.com/user-attachments/assets/11353a21-7336-48dc-9497-971e8100ae59)

However, it's clarified by Archon staff on the BoardGameGeek forum that Expert Effect uses are regained by each player individually at the start of their turn, not round. Source: [message link](https://boardgamegeek.com/thread/3356644/article/44766434#44766434).
![Screenshot_20240831-153210_Firefox_Beta](https://github.com/user-attachments/assets/07f61f4a-0778-4ae5-b489-e19ea5373cfb)

**Comment by rkurbatov** [comment]
That sounds more logical, agree. Like everything related to CASTLES/MACRO is performed per round basis (resources, tokens, astrology). And everything related to HEROES/MICRO is performed per turn basis.

Btw, then MP tokens are also should be rotated back at the start of the user turn, because you can use them only during your turn anyway. And it would be simpler to rotate them back simultaneously with moving cubes/crowns on the hero card to the starting position.

**Comment by Dima793** [comment]
UPD: a later clarification on Discord denies the earlier one. It's at the start of each round, after all. Source: [message link](https://discord.com/channels/740870068178649108/1211591995328299038/1282974288290517013)
![Screenshot_20240910-134654_Discord](https://github.com/user-attachments/assets/7ef6647b-715a-474d-a99c-822735cd1cf2)
