### ISSUE TITLE
Missing Temple in Field List

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#82]
Temple got lost somewhere) Also, Fountain of Youth and shrines. Are they not ready yet or you are not plannig to add them? If that is the case, i suggest adding at least on example with each symbol

**Comment by Heegu-sama** [comment]
There's space to add these but I haven't felt the need since these fields actually use the game's symbology correctly, making their effects very clear. The only thing that's not immediately apparent from the symbols is that the shrines, for example, are optional to use when you visit them. I'll think on this.

**Comment by omoprof** [comment]
at very least add pandora's box symbol

**Comment by Heegu-sama** [comment]
I can see where you're coming from with wanting to see these locations but I think this is one part where they used their symbols correctly on the tiles and it's very clear what all of these locations do at a glance. Also I'm lazy.

The latest PR has a much clearer and shorter description of what fields I haven't pictured there.
